### ISSUE TITLE
Discord.js@12

### ISSUE THREAD

**Issue by Timongcraft** [peterhanania/reaction-roles#7]
Can you please make a version with discord.js@13?
Becorse https://github.com/discord/discord-api-docs/discussions/4510

**Comment by Timong-craft** [comment]
And I can't contact you on dc because you didn't allow dms oder friendrequests :(

**Comment by peterhanania** [comment]
Well I’m current really busy but it I find time to do so I definitely will 😁

**Comment by Timongcraft** [comment]
Thanks

**Comment by Timongcraft** [comment]
Do you have a date or is this repo no longer active?
